/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics;

import airline.logic.Airline;

/**
 *
 * @author ADMIN
 */
public class AddStewardessesInterface extends javax.swing.JFrame {
private Airline airline;
    public AddStewardessesInterface(Airline airline) {
   this.airline = airline;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonGoWorker = new javax.swing.JButton();
        jButtonCustomerSupport = new javax.swing.JButton();
        jButtonFood = new javax.swing.JButton();
        jButtonSecurity = new javax.swing.JButton();
        jButtonExit5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("ADD STEWARDESSES ");

        jButtonGoWorker.setText("Back");
        jButtonGoWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoWorkerActionPerformed(evt);
            }
        });

        jButtonCustomerSupport.setText("Customer Support");
        jButtonCustomerSupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerSupportActionPerformed(evt);
            }
        });

        jButtonFood.setText("Food");
        jButtonFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoodActionPerformed(evt);
            }
        });

        jButtonSecurity.setText("Security");
        jButtonSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSecurityActionPerformed(evt);
            }
        });

        jButtonExit5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButtonExit5.setForeground(new java.awt.Color(0, 0, 0));
        jButtonExit5.setText("X");
        jButtonExit5.setToolTipText("");
        jButtonExit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExit5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jButtonCustomerSupport))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSecurity)
                            .addComponent(jButtonGoWorker)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonFood)
                                .addGap(8, 8, 8)))))
                .addContainerGap(353, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExit5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addComponent(jButtonExit5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jButtonCustomerSupport)
                .addGap(83, 83, 83)
                .addComponent(jButtonFood)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jButtonSecurity)
                .addGap(101, 101, 101)
                .addComponent(jButtonGoWorker)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGoWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoWorkerActionPerformed
        WorkerInterface w = new WorkerInterface(airline);
        w.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonGoWorkerActionPerformed

    private void jButtonCustomerSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerSupportActionPerformed
        AddStewardessesCustomerSupport ascs = new AddStewardessesCustomerSupport(airline);
        ascs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCustomerSupportActionPerformed

    private void jButtonFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoodActionPerformed
        AddStewardessesFood asf = new AddStewardessesFood(airline);
        asf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFoodActionPerformed

    private void jButtonSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSecurityActionPerformed
        AddStewardessesSecurity ase = new AddStewardessesSecurity(airline);
        ase.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSecurityActionPerformed

    private void jButtonExit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExit5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExit5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCustomerSupport;
    private javax.swing.JButton jButtonExit4;
    private javax.swing.JButton jButtonExit5;
    private javax.swing.JButton jButtonFood;
    private javax.swing.JButton jButtonGoWorker;
    private javax.swing.JButton jButtonSecurity;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
