/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics;

import airline.logic.Airline;

/**
 *
 * @author ADMIN
 */
public class FlightInterface extends javax.swing.JFrame {

private Airline airline;
    public FlightInterface(Airline airline) {
        this.airline = airline;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jButtonGoWorker = new javax.swing.JButton();
        jButtonGoRoute = new javax.swing.JButton();
        jButtonBackMenu = new javax.swing.JButton();
        jButtonAddFlights = new javax.swing.JButton();
        jButtonShowFlights = new javax.swing.JButton();
        jButtonSearchFlights = new javax.swing.JButton();
        jButtonExit5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabelTitle.setText("FLIGHT");

        jButtonGoWorker.setText("Worker");
        jButtonGoWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoWorkerActionPerformed(evt);
            }
        });

        jButtonGoRoute.setText("Route");
        jButtonGoRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoRouteActionPerformed(evt);
            }
        });

        jButtonBackMenu.setText("Menu");
        jButtonBackMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackMenuActionPerformed(evt);
            }
        });

        jButtonAddFlights.setText("Add");
        jButtonAddFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddFlightsActionPerformed(evt);
            }
        });

        jButtonShowFlights.setText("Show");
        jButtonShowFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowFlightsActionPerformed(evt);
            }
        });

        jButtonSearchFlights.setText("Search");
        jButtonSearchFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchFlightsActionPerformed(evt);
            }
        });

        jButtonExit5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButtonExit5.setForeground(new java.awt.Color(0, 0, 0));
        jButtonExit5.setText("X");
        jButtonExit5.setToolTipText("");
        jButtonExit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExit5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButtonAddFlights)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                        .addComponent(jButtonShowFlights))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonGoWorker)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBackMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTitle)
                        .addGap(19, 19, 19)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(261, 261, 261)
                            .addComponent(jButtonGoRoute))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(208, 208, 208)
                            .addComponent(jButtonSearchFlights)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jButtonExit5))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitle))
                .addGap(232, 232, 232)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearchFlights)
                    .addComponent(jButtonShowFlights)
                    .addComponent(jButtonAddFlights))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGoWorker)
                    .addComponent(jButtonGoRoute)
                    .addComponent(jButtonBackMenu))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGoRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoRouteActionPerformed
        RouteInterface r = new RouteInterface(airline);
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonGoRouteActionPerformed

    private void jButtonGoWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoWorkerActionPerformed
        WorkerInterface w = new WorkerInterface(airline);
        w.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonGoWorkerActionPerformed

    private void jButtonBackMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackMenuActionPerformed
        MenuInterface mi = new MenuInterface();
        mi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackMenuActionPerformed

    private void jButtonAddFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddFlightsActionPerformed
        AddFlightsInterface af = new AddFlightsInterface(airline);
        af.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAddFlightsActionPerformed

    private void jButtonShowFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowFlightsActionPerformed
        ShowFlightsInterface sf = new ShowFlightsInterface(airline);
        sf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonShowFlightsActionPerformed

    private void jButtonSearchFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchFlightsActionPerformed
        SearchFlightsInterface sef = new SearchFlightsInterface(airline);
        sef.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSearchFlightsActionPerformed

    private void jButtonExit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExit5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExit5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddFlights;
    private javax.swing.JButton jButtonBackMenu;
    private javax.swing.JButton jButtonExit5;
    private javax.swing.JButton jButtonGoRoute;
    private javax.swing.JButton jButtonGoWorker;
    private javax.swing.JButton jButtonSearchFlights;
    private javax.swing.JButton jButtonShowFlights;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
