/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics;

import Graphics.FlightInterface;
import Graphics.WorkerInterface;
import Graphics.RouteInterface;
import airline.logic.Airline;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JFrame;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class MenuInterface extends javax.swing.JFrame {

    private Airline airline;

    public MenuInterface() {
        airline = new Airline();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jButtonFlight = new javax.swing.JButton();
        jButtonWorker = new javax.swing.JButton();
        jButtonRoute = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setBackground(new java.awt.Color(0, 99, 154));
        jButtonExit.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(0, 0, 0));
        jButtonExit.setText("X");
        jButtonExit.setToolTipText("");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, 30));

        jButtonFlight.setText("Flight ");
        jButtonFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlightActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jButtonWorker.setText("Worker");
        jButtonWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWorkerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonWorker, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 70, -1));

        jButtonRoute.setText("Route");
        jButtonRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRouteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRoute, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/background.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-980, -10, 1770, 1220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);        
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlightActionPerformed
        FlightInterface f = new FlightInterface(airline);
        f.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonFlightActionPerformed

    private void jButtonWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWorkerActionPerformed
        WorkerInterface w = new WorkerInterface(airline);
        w.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonWorkerActionPerformed

    private void jButtonRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRouteActionPerformed
        RouteInterface r = new RouteInterface(airline);
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRouteActionPerformed

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonFlight;
    private javax.swing.JButton jButtonRoute;
    private javax.swing.JButton jButtonWorker;
    private javax.swing.JLabel jLabelBackground;
    // End of variables declaration//GEN-END:variables
}
