/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics;

import Graphics.FlightInterface;
import Graphics.RouteInterface;
import airline.logic.Airline;

/**
 *
 * @author ADMIN
 */
public class WorkerInterface extends javax.swing.JFrame {

   private Airline airline;
    public WorkerInterface(Airline airline) {
        this.airline = airline;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBackMenu = new javax.swing.JButton();
        jButtonGoFlight = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jButtonGoRute = new javax.swing.JButton();
        jButtonAddPilots = new javax.swing.JButton();
        jButtonShowPilots = new javax.swing.JButton();
        jButtonSearchPilots = new javax.swing.JButton();
        jButtonShowStewardesses = new javax.swing.JButton();
        jButtonAddStewardesses = new javax.swing.JButton();
        jButtonSearchStewardesses = new javax.swing.JButton();
        jButtonExit4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jButtonBackMenu.setText("Menu");
        jButtonBackMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackMenuActionPerformed(evt);
            }
        });

        jButtonGoFlight.setText("Flight");
        jButtonGoFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoFlightActionPerformed(evt);
            }
        });

        jLabelTitle.setText("WORKER");

        jButtonGoRute.setText("Route");
        jButtonGoRute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoRuteActionPerformed(evt);
            }
        });

        jButtonAddPilots.setText("Add Pilots");
        jButtonAddPilots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPilotsActionPerformed(evt);
            }
        });

        jButtonShowPilots.setText("Show Pilots");
        jButtonShowPilots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowPilotsActionPerformed(evt);
            }
        });

        jButtonSearchPilots.setText("Search Pilots");
        jButtonSearchPilots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchPilotsActionPerformed(evt);
            }
        });

        jButtonShowStewardesses.setText("Show Stewardesses");
        jButtonShowStewardesses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowStewardessesActionPerformed(evt);
            }
        });

        jButtonAddStewardesses.setText("Add Stewardesses");
        jButtonAddStewardesses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddStewardessesActionPerformed(evt);
            }
        });

        jButtonSearchStewardesses.setText("Search Stewardesses");
        jButtonSearchStewardesses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchStewardessesActionPerformed(evt);
            }
        });

        jButtonExit4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButtonExit4.setForeground(new java.awt.Color(0, 0, 0));
        jButtonExit4.setText("X");
        jButtonExit4.setToolTipText("");
        jButtonExit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExit4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGoFlight)
                    .addComponent(jButtonShowPilots)
                    .addComponent(jButtonShowStewardesses))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBackMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonGoRute)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonAddPilots)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSearchStewardesses)
                                    .addComponent(jButtonSearchPilots))
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonExit4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButtonAddStewardesses)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelTitle))
                    .addComponent(jButtonExit4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearchPilots)
                    .addComponent(jButtonShowPilots)
                    .addComponent(jButtonAddPilots))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonShowStewardesses)
                    .addComponent(jButtonAddStewardesses)
                    .addComponent(jButtonSearchStewardesses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGoFlight)
                    .addComponent(jButtonGoRute)
                    .addComponent(jButtonBackMenu))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackMenuActionPerformed
        MenuInterface mi = new MenuInterface();
        mi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackMenuActionPerformed

    private void jButtonGoFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoFlightActionPerformed
        FlightInterface f = new FlightInterface(airline);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonGoFlightActionPerformed

    private void jButtonGoRuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoRuteActionPerformed
        RouteInterface r = new RouteInterface(airline);
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonGoRuteActionPerformed

    private void jButtonShowPilotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowPilotsActionPerformed
        ShowPilotsInterface sp = new ShowPilotsInterface(airline);
        sp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonShowPilotsActionPerformed

    private void jButtonAddPilotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPilotsActionPerformed
        AddPilotsInterface ap = new AddPilotsInterface(airline);
        ap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAddPilotsActionPerformed

    private void jButtonSearchPilotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchPilotsActionPerformed
        SearchPilotsInterface sep = new SearchPilotsInterface(airline);
        sep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSearchPilotsActionPerformed

    private void jButtonShowStewardessesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowStewardessesActionPerformed
        ShowStewardessesInterface ss = new ShowStewardessesInterface(airline);
        ss.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonShowStewardessesActionPerformed

    private void jButtonAddStewardessesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddStewardessesActionPerformed
        AddStewardessesInterface as = new AddStewardessesInterface(airline);
        as.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAddStewardessesActionPerformed

    private void jButtonSearchStewardessesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchStewardessesActionPerformed
        SearchStewardessesInterface ses = new SearchStewardessesInterface(airline);
        ses.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSearchStewardessesActionPerformed

    private void jButtonExit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExit4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExit4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPilots;
    private javax.swing.JButton jButtonAddStewardesses;
    private javax.swing.JButton jButtonBackMenu;
    private javax.swing.JButton jButtonExit4;
    private javax.swing.JButton jButtonGoFlight;
    private javax.swing.JButton jButtonGoRute;
    private javax.swing.JButton jButtonSearchPilots;
    private javax.swing.JButton jButtonSearchStewardesses;
    private javax.swing.JButton jButtonShowPilots;
    private javax.swing.JButton jButtonShowStewardesses;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
